-- keep a handle to the notification so we can dismiss it
-- vim.g.recording_notif_handle = nil

return {
  -- "folke/noice.nvim",
  -- event = "VeryLazy",
  -- opts = {
  --   -- show @recording message
  --   routes = {
  --     {
  --       view = "notify",
  --       filter = { event = "msg_showmode" },
  --     },
  --   },
  -- },
  -- dependencies = {
  --   "MunifTanjim/nui.nvim",
  --   "rcarriga/nvim-notify",
  -- },
  -- config = function(_, opts)
  --   local noice = require("noice")
  --   noice.setup(opts)
  --
  --   -- not working :P
  --   -- special case: if enter recording, we should
  --   -- create a persistent notification
  --   vim.api.nvim_create_autocmd("RecordingEnter", {
  --     callback = function()
  --       local reg = vim.fn.reg_recording()
  --
  --       vim.g.recording_notif = noice.notify(
  --         ("recording @%s"):format(reg),
  --         "info",
  --         {
  --           timeout = false,
  --           replace = vim.g.recording_notif,
  --         }
  --       )
  --     end,
  --   })
  --
  --   vim.api.nvim_create_autocmd("RecordingLeave", {
  --     callback = function()
  --       if vim.g.recording_notif then
  --         vim.g.recording_notif:close()
  --         vim.g.recording_notif = nil
  --       end
  --     end,
  --   })
  -- end
}
